-- ========================================================
-- SUPABASE DDL SETUP FOR CSMS (Contractor Safety Management System)
-- ========================================================

-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- --------------------------------------------------------
-- 1. Table: profiles
-- Handles user profile information linked to Supabase Auth
-- --------------------------------------------------------
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade primary key,
    full_name text,
    role text,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

-- Policies for profiles
create policy "Public profiles are viewable by everyone." on public.profiles
    for select using (true);

create policy "Users can insert their own profile." on public.profiles
    for insert with check (auth.uid() = id);

create policy "Users can update their own profile." on public.profiles
    for update using (auth.uid() = id);

-- --------------------------------------------------------
-- 2. Table: documents
-- Core table storing the CSMS documents (HSE Plan, PJA, WIP, FE)
-- Used by src/utils/documentStore.ts
-- --------------------------------------------------------
create table if not exists public.documents (
    no bigint generated by default as identity primary key,
    nama text not null,
    added varchar(50) not null, -- formatted date string like "23-Nov-2025"
    added_date timestamp with time zone default timezone('utc'::text, now()) not null,
    status text not null check (status in ('New', 'On Progress', 'Done', 'On Review', 'Approved', 'Need Revision', 'Draft')),
    type text not null check (type in ('HSE Plan', 'PJA', 'WIP', 'FE')),
    file_name text null,
    file_path text null,
    nilai varchar(50) null -- optional rating/score
);

-- Enable RLS for documents
alter table public.documents enable row level security;

-- Policies for documents (For development, allow public anonymous read/write)
create policy "Allow read access to all users" on public.documents
    for select using (true);

create policy "Allow insert access to all users" on public.documents
    for insert with check (true);

create policy "Allow update access to all users" on public.documents
    for update using (true);

create policy "Allow delete access to all users" on public.documents
    for delete using (true);

-- --------------------------------------------------------
-- 3. Initial Mock Data for documents
-- Pre-populates the database with the default items
-- --------------------------------------------------------
insert into public.documents (nama, added, added_date, status, type, nilai)
values
    (
        'Pengadaan Time Charter 1 (one) Unit VLGC Laycan 19-20 Februari 2024 (LPGC SC Commander LVII)',
        '23-Nov-2025',
        '2025-11-23 00:00:00+00',
        'New',
        'HSE Plan',
        null
    ),
    (
        'Pengadaan Time Charter 1 (satu) Unit Small 2 LPGC Pressurized Laycan 20-21 Februari 2024 (LPGC Gas Laura)',
        '19-Oct-2025',
        '2025-10-19 00:00:00+00',
        'New',
        'HSE Plan',
        null
    ),
    (
        'LPGC Jenggala',
        '06-Aug-2025',
        '2025-08-06 00:00:00+00',
        'Done',
        'PJA',
        '6.00'
    ),
    (
        'Time Charter 1 (satu) Unit Small 2 LPGC Pressurized Laycan 10-11 Maret 2024 (LPGC Gas Artemis)',
        '10-May-2025',
        '2025-05-10 00:00:00+00',
        'Done',
        'PJA',
        '5.00'
    ),
    (
        'Pengadaan Time Charter 1 (satu) unit small LPGC Pressurized Laycan 25-26 April 2024 (LPGC Gas Indonesia II)',
        '10-May-2025',
        '2025-05-10 00:00:00+00',
        'Done',
        'WIP',
        null
    ),
    (
        'Pengadaan Time Charter 1 (satu) unit small LPGC Pressurized Laycan 23-24 Mei 2024 (LPGC Gas Kalimantan)',
        '10-May-2025',
        '2025-05-10 00:00:00+00',
        'On Progress',
        'WIP',
        null
    ),
    (
        'Pengadaan COA 1 (satu) Unit Small 1 LPGC Pressurized Laycan 10-12 Juni 2024 (LPGC AE Gas)',
        '10-May-2025',
        '2025-05-10 00:00:00+00',
        'On Progress',
        'WIP',
        null
    ),
    (
        'Pengadaan Time Charter 1 (satu) Unit Midsize LPG Laycan 24-25 Juni 2024 (LPGC Gas Nusa)',
        '10-May-2025',
        '2025-05-10 00:00:00+00',
        'Done',
        'FE',
        null
    ),
    (
        'Pengadaan Time Charter 1 (satu) Unit Midsize LPG Laycan 15-16 Juli 2024 (LPGC Gas Sofia)',
        '12-Apr-2025',
        '2025-04-12 00:00:00+00',
        'Done',
        'FE',
        null
    )
on conflict do nothing;

-- --------------------------------------------------------
-- 4. Trigger for automatic Profile creation
-- Trigger to automatically create a profile record when a user registers
-- --------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''),
    coalesce(new.raw_user_meta_data->>'role', 'Officer')
  );
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ========================================================
-- OPTIONAL: Extended tables to store full Wizard assessment details
-- ========================================================

-- Table for full HSE Plan details
create table if not exists public.hse_plan_submissions (
    id bigint generated by default as identity primary key,
    document_no bigint references public.documents(no) on delete cascade unique,
    vendor_name text,
    project_name text,
    evaluation_date date,
    evaluator_name text,
    lokasi_pekerjaan text,
    pic_jabatan text,
    matrix_scores jsonb, -- Storing all questionnaire scores in a single JSON structure
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.hse_plan_submissions enable row level security;
create policy "Allow read access to hse_plan_submissions" on public.hse_plan_submissions for select using (true);
create policy "Allow write access to hse_plan_submissions" on public.hse_plan_submissions for all using (true);

-- Table for full Pre-Job Assessment (PJA) details
create table if not exists public.pja_submissions (
    id bigint generated by default as identity primary key,
    document_no bigint references public.documents(no) on delete cascade unique,
    vendor_name text,
    project_name text,
    bidang_usaha text,
    evaluation_date date,
    evaluator_name text,
    pic_jabatan text,
    lokasi_pekerjaan text,
    answers jsonb, -- Storing YES/NO/NO_NEED questionnaires in JSON
    notes jsonb, -- Storing notes for each question
    due_date date,
    keterangan text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.pja_submissions enable row level security;
create policy "Allow read access to pja_submissions" on public.pja_submissions for select using (true);
create policy "Allow write access to pja_submissions" on public.pja_submissions for all using (true);

-- Table for full Work In Progress (WIP) details
create table if not exists public.wip_submissions (
    id bigint generated by default as identity primary key,
    document_no bigint references public.documents(no) on delete cascade unique,
    stage text,
    nama_perusahaan text,
    jenis_pekerjaan text,
    lokasi_pekerjaan text,
    tanggal_penilaian date,
    evaluator text,
    lagging_indicators jsonb, -- JSON with target, actual, sanksi
    leading_indicators jsonb, -- JSON with target, actual, sanksi
    pja_lagging jsonb,
    pja_leading jsonb,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.wip_submissions enable row level security;
create policy "Allow read access to wip_submissions" on public.wip_submissions for select using (true);
create policy "Allow write access to wip_submissions" on public.wip_submissions for all using (true);

-- Table for full Final Evaluation (FE) details
create table if not exists public.fe_submissions (
    id bigint generated by default as identity primary key,
    document_no bigint references public.documents(no) on delete cascade unique,
    project_name text,
    total_temuan integer,
    status_temuan text,
    hse_score numeric(5,2),
    rekomendasi_close text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.fe_submissions enable row level security;
create policy "Allow read access to fe_submissions" on public.fe_submissions for select using (true);
create policy "Allow write access to fe_submissions" on public.fe_submissions for all using (true);
